/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.cliente;

import controlador.cliente.ControladorVistaGestionReserva;
import excepciones.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import modelo.*;
import vista.VistaInicioSesion;

public class VistaGestionReserva extends javax.swing.JPanel {
    private Cliente cliente;
    private ControladorVistaGestionReserva controlador;
    /**
     * Creates new form VitaViajes
     */
    public VistaGestionReserva(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
        this.controlador = new ControladorVistaGestionReserva();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        ViajeSinReserva = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        btnVenderTiqueteSinReserva = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViajes = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 153, 204)));

        ViajeSinReserva.setBackground(new java.awt.Color(255, 255, 255));
        ViajeSinReserva.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Reserva", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad de Puestos");

        txtCant.setBackground(new java.awt.Color(204, 204, 204));
        txtCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantActionPerformed(evt);
            }
        });

        btnVenderTiqueteSinReserva.setBackground(new java.awt.Color(0, 153, 204));
        btnVenderTiqueteSinReserva.setForeground(new java.awt.Color(255, 255, 255));
        btnVenderTiqueteSinReserva.setText("Vender Tiquete");
        btnVenderTiqueteSinReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderTiqueteSinReservaActionPerformed(evt);
            }
        });

        tblViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Origen", "Destino", "Fecha salida", "Fecha llegada", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tblViajes);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Seleciona el viaje el cual va a vender los tiquetes:");

        btnCerrarSesion.setBackground(new java.awt.Color(0, 153, 204));
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViajeSinReservaLayout = new javax.swing.GroupLayout(ViajeSinReserva);
        ViajeSinReserva.setLayout(ViajeSinReservaLayout);
        ViajeSinReservaLayout.setHorizontalGroup(
            ViajeSinReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViajeSinReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViajeSinReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViajeSinReservaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ViajeSinReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVenderTiqueteSinReserva)
                            .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(ViajeSinReservaLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesion)
                        .addGap(18, 18, 18))))
        );
        ViajeSinReservaLayout.setVerticalGroup(
            ViajeSinReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViajeSinReservaLayout.createSequentialGroup()
                .addGroup(ViajeSinReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViajeSinReservaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViajeSinReservaLayout.createSequentialGroup()
                        .addComponent(btnCerrarSesion)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(ViajeSinReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ViajeSinReservaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(ViajeSinReservaLayout.createSequentialGroup()
                        .addGroup(ViajeSinReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVenderTiqueteSinReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(ViajeSinReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViajeSinReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        VistaInicioSesion vi = new VistaInicioSesion();
        vi.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void txtCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantActionPerformed

    private void btnVenderTiqueteSinReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderTiqueteSinReservaActionPerformed
        if (!validarCampos()) {
            try {
                int cantPuestos = Integer.parseInt(txtCant.getText());
                Viaje viaje = viajeTabla();
                Reserva reserva = new Reserva();
                JOptionPane.showMessageDialog(null, "Se vendio el tiquete con éxito");
                vaciarCampos();
                llenarTablaViajes();
            
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Error en el formato de los datos ingresados.");
            } catch (NoSeleccionoNadaException ex) {
                Logger.getLogger(VistaGestionReserva.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe llenar los campos correspondientes");
        }
    }//GEN-LAST:event_btnVenderTiqueteSinReservaActionPerformed
    public void vaciarCampos() {
        txtCant.setText(null);
    }

    public boolean validarCampos() {
        return txtCant.getText().isEmpty();
    }
    
    public Viaje viajeTabla() throws NoSeleccionoNadaException {
        int filaSeleccionada = tblViajes.getSelectedRow();
        if (filaSeleccionada == -1) {
            throw new NoSeleccionoNadaException();
        }
        Object id = tblViajes.getValueAt(filaSeleccionada, 0);
        if (!(id instanceof Integer)) {
            throw new IllegalArgumentException("El ID de viaje seleccionado no es un número válido.");
        }
        System.out.println("ID seleccionado de la tabla: " + id);
        Viaje viaje = controlador.buscarViajeTabla((Integer) id);
        if (viaje == null) {
            System.out.println("El viaje con ID " + id + " no está en la empresa.");
        }
        return viaje;
    }

    private void llenarTablaViajes() {
        DefaultTableModel model = new DefaultTableModel() {
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        model.setColumnIdentifiers(new Object[]{"id", "Origen", "Destino", "Fecha Salida", "Fecha llegada", "Valor"});
        ArrayList<Caseta> aux = controlador.getListaCasetas();
        for (Caseta caseta : aux) {
            ArrayList<Viaje> auxViajes = caseta.getEmpresa().getViajes();
            for (Viaje auxViaje : auxViajes){
                Viaje viaje = auxViaje;
                model.addRow(new Object[]{
                viaje.getIdViaje(),
                viaje.getOrigen(),
                viaje.getDestino(),
                viaje.getFechaSalida(),
                viaje.getFechallegada(),
                viaje.getValor()
            });
            }
            

        }
        tblViajes.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ViajeSinReserva;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnVenderTiqueteSinReserva;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViajes;
    private javax.swing.JTextField txtCant;
    // End of variables declaration//GEN-END:variables
}
