/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.terminal;

import java.awt.BorderLayout;
import modelo.Persona;


/**
 *
 * @author DARIO LOPEZ
 */
public class vistaAdminTerminal extends javax.swing.JFrame {
    /**
     * Creates new form vistaAdminTerminal
     */
    public vistaAdminTerminal(Persona persona) {
        initComponents();
        setLocationRelativeTo(this);
        adminTerminalName.setText(persona.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        content = new javax.swing.JPanel();
        labelBienvenido = new javax.swing.JLabel();
        adminTerminalName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        administradoresFlota = new javax.swing.JMenu();
        menuGestionAdminFlota = new javax.swing.JMenuItem();
        GestionCasetas = new javax.swing.JMenu();
        MenuGestionCaseta = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 153, 204)));

        labelBienvenido.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 48)); // NOI18N
        labelBienvenido.setForeground(new java.awt.Color(0, 0, 0));
        labelBienvenido.setText("BIENVENIDO");

        adminTerminalName.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        adminTerminalName.setForeground(new java.awt.Color(0, 0, 0));
        adminTerminalName.setText("adminTerminalNombre");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("🌟 Panel de gestión del terminal 🌟");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cada acción que realices aquí contribuye a una operación fluida y bien organizada. ");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Seleccione una de las opciones del menú superior para gestionar los recursos:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Administradores de Flota:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tienes el poder de mantener a nuestro equipo de administradores de flota siempre actualizado.");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Añade nuevos supervisores, consulta detalles, actualiza información o elimina registros cuando");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("sea necesario. Una flota bien gestionada es sinónimo de eficiencia y seguridad.");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Empresas:");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Gestiona las empresas asociadas de manera efectiva. Desde registrar nuevas empresas");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("hasta revisar y actualizar sus datos, tu rol es fundamental para asegurar que cada");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("socio del terminal esté bien atendido y registrado.");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("✨ Cada actualización es un paso hacia un terminal más organizado y confiable.");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText(" ¡Gracias por tu dedicación! ✨");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Captura de pantalla 2024-10-30 183431 (1).png"))); // NOI18N
        jLabel15.setText("jLabel4");

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText(" ©TheCharles'sCousin'sCompany");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addGap(0, 146, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(labelBienvenido))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(adminTerminalName, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel2))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(labelBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(adminTerminalName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addComponent(jLabel10)
                .addGap(0, 0, 0)
                .addComponent(jLabel11)
                .addGap(0, 0, 0)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(0, 0, 0)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15))
                .addContainerGap())
        );

        administradoresFlota.setText("Administradores Flota");

        menuGestionAdminFlota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/User.jpg"))); // NOI18N
        menuGestionAdminFlota.setText("Gestion");
        menuGestionAdminFlota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionAdminFlotaActionPerformed(evt);
            }
        });
        administradoresFlota.add(menuGestionAdminFlota);

        jMenuBar1.add(administradoresFlota);

        GestionCasetas.setText("Casetas");

        MenuGestionCaseta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Caseta.jpg"))); // NOI18N
        MenuGestionCaseta.setText("Gestion");
        MenuGestionCaseta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGestionCasetaActionPerformed(evt);
            }
        });
        GestionCasetas.add(MenuGestionCaseta);

        jMenuBar1.add(GestionCasetas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGestionAdminFlotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionAdminFlotaActionPerformed
        VistaGestionAdministradorFlota vt = new VistaGestionAdministradorFlota();
        vt.setSize(885, 671);
        vt.setLocation(0,0);
        content.removeAll();
        content.add(vt, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_menuGestionAdminFlotaActionPerformed

    private void MenuGestionCasetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGestionCasetaActionPerformed
        VistaGestionCaseta vt = new VistaGestionCaseta();
        vt.setSize(885, 671);
        vt.setLocation(0,0);
        
        content.removeAll();
        content.add(vt, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_MenuGestionCasetaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu GestionCasetas;
    private javax.swing.JMenuItem MenuGestionCaseta;
    private javax.swing.JLabel adminTerminalName;
    private javax.swing.JMenu administradoresFlota;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelBienvenido;
    private javax.swing.JMenuItem menuGestionAdminFlota;
    // End of variables declaration//GEN-END:variables
}
